### ISSUE TITLE
Chapter 6_3/4: duplicate users added to state.users with createPost

### ISSUE THREAD

**Issue by mdbkdda** [PacktPublishing/Learning-Redux#3]
Once createPost completes, .then(result => fetchUser(result.user)(dispatch) is called, which adds the user to the list of users, even when that user already exists in the list.

To fix this one could do one of the following:
1. Change the user reducer for FETCH_USER_SUCCESS so that it doesn't add the user to the list if it is already there.
2. Don't call fetchUser in the first place <== this is what I think would be best since we don't want to call the server unnecessarily.

I wish I knew how to implement #2, since I think it is the best solution.

**Comment by omnidan** [comment]
@mdbkdda As far as I can see, the first solution is already implemented:

```
  if (type === FETCH_USER_SUCCESS) {
    return [ ...state, action.result ]
  }
```

To implement the second solution, you need to:

- pass the current `users` state to the CreatePost component
- check if the username already exists in the `users` state
- pass a `doFetchUser` flag to the action creator
- do not fetch user if this flag is set to `false`

You can see my implementation for this here: https://github.com/PacktPublishing/Learning-Redux/pull/6/commits/95bb658ac902ab7dd8d7a67dddb409c594e8d44a
